name: compile_and_build

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: add x to before install script
      run: chmod +x tools/before_install.sh
    - name: run before install
      run: ./tools/before_install.sh
    - name: add x to build script
      run: chmod +x tools/build.sh
    - name: run build
      run: ./tools/build.sh
    - name: upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/OHS_F437.bin
        asset_name: OHS_F437.bin
        tag: ${{ github.ref }}
        overwrite: true
